// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var Attendee;

  window.DWX || (window.DWX = {});

  window.DWX.Attendee = Attendee = (function() {
    function Attendee(input) {
      this.Id = input.Id;
      this.LastName = input.Title;
      this.FirstName = input.FirstName;
    }

    return Attendee;

  })();

}).call(this);
