// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var ManageBugsViewModel,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.DWX || (window.DWX = {});

  window.DWX.ManageBugsViewModel = ManageBugsViewModel = (function() {
    function ManageBugsViewModel() {
      this.onLoaded = __bind(this.onLoaded, this);
      this.deleteListItem = __bind(this.deleteListItem, this);
      this.init = __bind(this.init, this);
      this.items = ko.observableArray([]);
      this.repository = new DWX.SharePointListRepository('DWX Attendees', "/?$select=Id,Title,FirstName");
    }

    ManageBugsViewModel.prototype.init = function() {
      this.items.removeAll();
      return this.repository.readAll(this.onLoaded);
    };

    ManageBugsViewModel.prototype.deleteListItem = function(listItem) {
      var _this = this;
      return this.repository.deleteItem(listItem.Id, function() {
        return _this.items.remove(listItem);
      });
    };

    ManageBugsViewModel.prototype.onLoaded = function(result) {
      var attendee, _i, _len, _ref, _results;
      _ref = result.d.results;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        attendee = _ref[_i];
        _results.push(this.items.push(new DWX.Attendee(attendee)));
      }
      return _results;
    };

    return ManageBugsViewModel;

  })();

}).call(this);
