// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  window.DWX || (window.DWX = {});

  window.DWX.buildUrl = function(appendix) {
    return _spPageContextInfo.webAbsoluteUrl + appendix;
  };

  window.DWX.getFromREST = function(url, onSuccess, onError) {
    var params;
    params = {
      url: url,
      type: "GET",
      headers: {
        "Accept": "application/json; odata=verbose"
      }
    };
    return $.ajax(params).done(onSuccess).fail(onError);
  };

  window.DWX.deleteListItem = function(url, onSuccess, onError) {
    var params;
    params = {
      url: url,
      type: "POST",
      headers: {
        "X-RequestDigest": $("#__REQUESTDIGEST").val(),
        "IF-MATCH": "*",
        "X-HTTP-Method": "DELETE"
      }
    };
    return $.ajax(params).done(onSuccess).fail(onError);
  };

  window.DWX.buildPayload = function(listName, listItemProperties) {
    var listItemType, p, payload;
    listItemType = "SP.Data." + listName.charAt(0).toUpperCase() + listName.slice(1) + "ListItem";
    payload = {
      "__metadata": {
        "type": listItemType
      }
    };
    for (p in listItemProperties) {
      payload[p] = listItemProperties[p];
    }
    return payload;
  };

  window.DWX.updateListItem = function(url, listName, listItemProperties, onSuccess, onError) {
    var params, payload, payloadAsJson;
    payload = DWX.buildPayload(listName, listItemProperties);
    payloadAsJson = JSON.stringify(payload);
    params = {
      url: url,
      type: "POST",
      contentType: "application/json;odata=verbose",
      data: payloadAsJson,
      headers: {
        "accept": "application/json;odata=verbose",
        "X-RequestDigest": $("#__REQUESTDIGEST").val(),
        "X-HTTP-Method": "MERGE",
        "content-type": "application/json;odata=verbose",
        "If-Match": "*"
      }
    };
    return $.ajax(params).done(onSuccess).fail(onError);
  };

  window.DWX.createListItem = function(url, listName, listItemProperties, onSuccess, onError) {
    var params, payload;
    payload = DWX.buildPayload(listName, listItemProperties);
    params = {
      url: url,
      type: "POST",
      data: JSON.stringify(payload),
      headers: {
        "Accept": "application/json; odata=verbose",
        "content-type": "application/json;odata=verbose",
        "X-RequestDigest": $("#__REQUESTDIGEST").val()
      }
    };
    return $.ajax(params).done(onSuccess).fail(onError);
  };

}).call(this);
