// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var SharePointListRepository;

  window.DWX || (window.DWX = {});

  window.DWX.SharePointListRepository = SharePointListRepository = (function() {
    function SharePointListRepository(listName, restParams) {
      this.listName = listName;
      this.restParams = restParams;
    }

    SharePointListRepository.prototype.readAll = function(onSuccess, onError) {
      var url;
      url = DWX.buildUrl("/_api/web/lists/getbytitle('" + this.listName + "')/items" + this.restParams);
      return DWX.getFromREST(url, onSuccess, onError);
    };

    SharePointListRepository.prototype.readItems = function(restParameter, onSuccess, onError) {
      var url;
      url = DWX.buildUrl("/_api/web/lists/getbytitle('" + this.listName + "')/items" + restParameter);
      return DWX.getFromREST(url, onSuccess, onError);
    };

    SharePointListRepository.prototype.createItem = function(listItemProperties, onSuccess, onError) {
      var url;
      url = DWX.buildUrl("/_api/web/lists/GetByTitle('" + this.listName + "')/items");
      return DWX.createListItem(url, this.listName, listItemProperties, onSuccess, onError);
    };

    SharePointListRepository.prototype.deleteItem = function(listItemId, onSuccess, onError) {
      var url;
      url = DWX.buildUrl("/_api/web/lists/getbytitle('" + this.listName + "')/items(" + listItemId + ")");
      return DWX.deleteListItem(url, onSuccess, onError);
    };

    SharePointListRepository.prototype.assignItemTo = function(listItemId, userId, onSuccess, onError) {
      var item, onCompleted, url;
      url = DWX.buildUrl("/_api/web/lists/getbytitle('" + this.listName + "')/items(" + listItemId + ")");
      item = {
        "EI_AssignedToId": userId
      };
      onCompleted = function(data) {
        var _ref;
        return (_ref = onSuccess(userId)) != null ? _ref : onSuccess;
      };
      return DWX.updateListItem(url, this.listName, item, onCompleted, onError);
    };

    SharePointListRepository.prototype.getUserDisplayName = function(userId, onSuccess, onError) {
      var onCompleted, url;
      url = DWX.buildUrl("/_api/web/GetUserById(" + userId + ")/?$select=Title");
      onCompleted = function(data) {
        var _ref;
        return (_ref = onSuccess(data.d.Title)) != null ? _ref : onSuccess;
      };
      return DWX.getFromREST(url, onCompleted, onError);
    };

    SharePointListRepository.prototype.getAuthorDisplayName = function(model, onSuccess, onError) {
      var onCompleted;
      onCompleted = function(userName) {
        var _ref;
        model.Author = userName;
        return (_ref = onSuccess(model)) != null ? _ref : onSuccess;
      };
      return this.getUserDisplayName(model.AuthorId, onCompleted, onError);
    };

    return SharePointListRepository;

  })();

}).call(this);
